### ISSUE TITLE
Change GHA Runner image name

### ISSUE THREAD

**Issue by jeefy** [cncf/automation#14]
Ensure the docker build/workflow for the GHA Runner image is named something like `cncf/gha-runner` not `cncf/automation` -- copying the workflow over from the other repo defaulted the Image name to be the name of the repo 😅

**Comment by RobertKielty** [comment]
Line that needs to change

https://github.com/cncf/automation/blob/e3b00b65bd6ce03fb05806480683a7f0bbc161bd/.github/workflows/publish-image.yml#L22

@jeefy Should we call it the `cncf/[external|equinix|whatever]-gha-runner` to indicate that the image is intended for use on the ARC(s) that we manage, own and operate off-GitHub?
